---


- name: DevOps challenge app test
  hosts: all
  become: yes
  become_user: vagrant
  become_method: sudo

  vars:
    wsgi_file: app.py
    # Directory to where repository will be cloned
    workdir: /webapps/devops

    # Repository to check out -- YOU MUST CHANGE THIS
    # repo must contain a local.yml file at top level
    #repo_url: git://github.com/sfromm/ansible-playbooks.git
    repo_url: https://bitbucket.org/azneita/devops-challenge.git

  tasks:
    - name: Install ansible
      apt: 
        name: ['ansible', 'git', 'python-pip', 'daemon', 'supervisor', 'uwsgi', 'uwsgi-plugin-python'] 
        state: present
      become: yes
      become_user: root

    - name: Create local directory to work from
      file: 
        path: /webapps
        state: directory
        owner: vagrant
        group: vagrant
        mode: 0775
        recurse: yes
      become: yes
      become_user: root
    
    - name: Checkout DevOps challenge source code
      git:
        repo: "{{ repo_url }}"
        dest: "{{ workdir }}"
        clone: yes

    - name: Install Python Modules
      pip: 
        requirements: "{{ workdir }}/requirements.txt"
      become: yes
      become_user: root

    - name: create supervisor program config
      action: template src=templates/supervisor.ini dest=/etc/supervisor/conf.d/app.conf
      notify:
        - restart app
      become: yes
      become_user: root

  handlers:
    - name: restart app
      action: supervisorctl name=app state=restarted
      become: yes
      become_user: root