---

- name: DevOps challenge app test
  hosts: all
  become: true
  remote_user: vagrant
  become_method: sudo

  vars:
    wsgi_file: app.py
    # Directory to where repository will be cloned
    workdir: /webapps/devops

    # Repository to check out -- YOU MUST CHANGE THIS
    # repo must contain a local.yml file at top level
    #repo_url: git://github.com/sfromm/ansible-playbooks.git
    repo_url: https://bitbucket.org/azneita/devops-challenge.git
    logrotate_scripts:
      - name: app-options
        path: /webapps/devops/app.log
        options:
          - daily
          - size 10M
          - missingok

  roles:
    - ansible-logrotate

  tasks:
    - name: Install ansible
      apt: 
        name: ['ansible', 'git', 'python-pip', 'daemon', 'supervisor', 'uwsgi', 'uwsgi-plugin-python'] 
        state: present

    - name: Create local directory to work from
      file: 
        path: /webapps
        state: directory

    - name: Checkout DevOps challenge source code
      git:
        repo: "{{ repo_url }}"
        dest: "{{ workdir }}"
        clone: yes

    - name: Install Python Modules
      pip: 
        requirements: "{{ workdir }}/requirements.txt"

    - name: create supervisor program config
      action: template src=templates/supervisor.ini dest=/etc/supervisor/conf.d/app.conf
      notify:
        - restart app
    
    - name: supervisor reload
      shell: supervisorctl reload
      
    - name: Verify logrotate config check passes
      shell: logrotate -d "{{ logrotate_conf_dir }}{{ item.name }}"
      with_items: "{{ logrotate_scripts }}"
      register: logrotate_app
      failed_when: "'error' in logrotate_app.stderr"

  handlers:
    - name: restart app
      action: supervisorctl name=app state=restarted